version: 2.1

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  build-report:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter pub run dart_code_metrics:metrics analyze lib --reporter=html

      - store_artifacts:
          path: metrics
workflows:
  generate-report:
    when: << pipelines.parameters.GHA_Action >>
    jobs:
      - build-report
