version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: sudo apt-get update
      - run: flutter pub get
      - run: flutter pub run dart_code_metrics:metrics analyze lib --reporter=html

      - store_artifacts:
        path: metrics
