# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "12.x"
      FLUTTER_VERSION: "2.10.4"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.4"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: echo ${{ github.event.pull_request.base.ref }}

  create-release-draft:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'refs/heads/main')
    permissions:
      contents: write
      pull-requests: write
    name: "Create Release Notes"
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
